/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsShell: typeof import('./src/components/AnalyticsShell.vue')['default']
    Badge: typeof import('./src/components/ui/Badge.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    CodeMirrorEditor: typeof import('./src/components/CodeMirrorEditor.vue')['default']
    CustomMetricsDashboard: typeof import('./src/components/CustomMetricsDashboard.vue')['default']
    CustomWidgetCard: typeof import('./src/components/CustomWidgetCard.vue')['default']
    CustomWidgetDialog: typeof import('./src/components/CustomWidgetDialog.vue')['default']
    DashboardOverview: typeof import('./src/components/DashboardOverview.vue')['default']
    DashboardSidebar: typeof import('./src/components/DashboardSidebar.vue')['default']
    Dialog: typeof import('./src/components/ui/Dialog.vue')['default']
    DialogDescription: typeof import('./src/components/ui/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/ui/DialogTitle.vue')['default']
    EChart: typeof import('./src/components/charts/EChart.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    IntegrationDetailsCard: typeof import('./src/components/IntegrationDetailsCard.vue')['default']
    IntegrationsOverview: typeof import('./src/components/IntegrationsOverview.vue')['default']
    Label: typeof import('./src/components/ui/Label.vue')['default']
    NotificationDetailsCard: typeof import('./src/components/NotificationDetailsCard.vue')['default']
    NotificationsOverview: typeof import('./src/components/NotificationsOverview.vue')['default']
    Progress: typeof import('./src/components/ui/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./src/components/ui/Separator.vue')['default']
    Skeleton: typeof import('./src/components/ui/Skeleton.vue')['default']
    Switch: typeof import('./src/components/ui/Switch.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/TabsTrigger.vue')['default']
    Textarea: typeof import('./src/components/ui/Textarea.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    WorkflowCardDetails: typeof import('./src/components/WorkflowCardDetails.vue')['default']
    WorkflowOverview: typeof import('./src/components/WorkflowOverview.vue')['default']
  }
}
