/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/ui/Badge.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    ColumnHeaderFilter: typeof import('./src/components/workflows/ColumnHeaderFilter.vue')['default']
    ColumnSelector: typeof import('./src/components/workflows/ColumnSelector.vue')['default']
    DashboardList: typeof import('./src/components/analytics/DashboardList.vue')['default']
    DashboardSelector: typeof import('./src/components/analytics/DashboardSelector.vue')['default']
    DateTimeRangePicker: typeof import('./src/components/DateTimeRangePicker.vue')['default']
    DeleteIntegrationDialog: typeof import('./src/components/integrations/DeleteIntegrationDialog.vue')['default']
    DeleteNotificationDialog: typeof import('./src/components/notifications/DeleteNotificationDialog.vue')['default']
    Dialog: typeof import('./src/components/ui/Dialog.vue')['default']
    DialogDescription: typeof import('./src/components/ui/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/ui/DialogTitle.vue')['default']
    DropdownMenu: typeof import('./src/components/ui/DropdownMenu.vue')['default']
    GitHubAppLinkDialog: typeof import('./src/components/integrations/GitHubAppLinkDialog.vue')['default']
    GitHubInstallation: typeof import('./src/components/integrations/GitHubInstallation.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    IntegrationCard: typeof import('./src/components/integrations/IntegrationCard.vue')['default']
    IntegrationDetailsCard: typeof import('./src/components/integrations/IntegrationDetailsCard.vue')['default']
    IntegrationHeader: typeof import('./src/components/integrations/IntegrationHeader.vue')['default']
    Label: typeof import('./src/components/ui/Label.vue')['default']
    MetricWidget: typeof import('./src/components/analytics/widgets/MetricWidget.vue')['default']
    NotificationCard: typeof import('./src/components/notifications/NotificationCard.vue')['default']
    NotificationDetailsCard: typeof import('./src/components/notifications/NotificationDetailsCard.vue')['default']
    NotificationFilters: typeof import('./src/components/notifications/NotificationFilters.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Popover: typeof import('./src/components/ui/Popover.vue')['default']
    Progress: typeof import('./src/components/ui/Progress.vue')['default']
    RecentWorkflowRuns: typeof import('./src/components/dashboard/RecentWorkflowRuns.vue')['default']
    RotateSecretDialog: typeof import('./src/components/integrations/RotateSecretDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./src/components/ui/Separator.vue')['default']
    Skeleton: typeof import('./src/components/ui/Skeleton.vue')['default']
    StatCards: typeof import('./src/components/dashboard/StatCards.vue')['default']
    StatusDistributionChart: typeof import('./src/components/dashboard/StatusDistributionChart.vue')['default']
    Switch: typeof import('./src/components/ui/Switch.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/TabsTrigger.vue')['default']
    Textarea: typeof import('./src/components/ui/Textarea.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UnlinkInstallationDialog: typeof import('./src/components/integrations/UnlinkInstallationDialog.vue')['default']
    ViewManager: typeof import('./src/components/workflows/ViewManager.vue')['default']
    WebhookCredentials: typeof import('./src/components/integrations/WebhookCredentials.vue')['default']
    WebhookEventEditor: typeof import('./src/components/integrations/WebhookEventEditor.vue')['default']
    WidgetGrid: typeof import('./src/components/analytics/WidgetGrid.vue')['default']
    WidgetWrapper: typeof import('./src/components/analytics/WidgetWrapper.vue')['default']
    WorkflowCardDetails: typeof import('./src/components/workflows/WorkflowCardDetails.vue')['default']
    WorkflowJobRow: typeof import('./src/components/workflows/WorkflowJobRow.vue')['default']
    WorkflowTable: typeof import('./src/components/workflows/WorkflowTable.vue')['default']
    WorkflowTableRow: typeof import('./src/components/workflows/WorkflowTableRow.vue')['default']
    WorkflowToolbar: typeof import('./src/components/workflows/WorkflowToolbar.vue')['default']
  }
}
