CREATE ROLE "gitgazer_analyst" WITH NOINHERIT;--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "gitgazer"."notification_rules" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "gitgazer"."ws_connections" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."enterprises" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."events" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."integrations" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."organizations" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."pull_requests" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."repositories" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."user" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."user-assignments" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."workflow_jobs" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."workflow_run_pull_requests" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation analyst" ON "github"."workflow_runs" AS PERMISSIVE FOR SELECT TO "gitgazer_analyst" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));