CREATE ROLE "gitgazer_mcp" WITH NOINHERIT;--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."enterprises" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."integrations" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."organizations" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."pull_requests" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."repositories" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."user" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."workflow_jobs" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."workflow_run_pull_requests" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));--> statement-breakpoint
CREATE POLICY "tenant separation mcp" ON "github"."workflow_runs" AS PERMISSIVE FOR SELECT TO "gitgazer_mcp" USING (integration_id = ANY(string_to_array(NULLIF(current_setting('rls.integration_ids', TRUE), ''), ',')::uuid[]));