/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BooleanChip: typeof import('./src/components/BooleanChip.vue')['default']
    ColumnFilter: typeof import('./src/components/ColumnFilter.vue')['default']
    IntegrationCard: typeof import('./src/components/IntegrationCard.vue')['default']
    IntegrationDetailsCard: typeof import('./src/components/IntegrationDetailsCard.vue')['default']
    IntegrationsOverview: typeof import('./src/components/IntegrationsOverview.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NotificationCard: typeof import('./src/components/NotificationCard.vue')['default']
    NotificationDetailsCard: typeof import('./src/components/NotificationDetailsCard.vue')['default']
    NotificationsOveview: typeof import('./src/components/NotificationsOveview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkflowCard: typeof import('./src/components/WorkflowCard.vue')['default']
    WorkflowCardDetails: typeof import('./src/components/WorkflowCardDetails.vue')['default']
    WorkflowOverview: typeof import('./src/components/WorkflowOverview.vue')['default']
  }
}
