/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalyticsOverview: typeof import('./src/components/AnalyticsOverview.vue')['default']
    BooleanChip: typeof import('./src/components/BooleanChip.vue')['default']
    ColumnHeader: typeof import('./src/components/ColumnHeader.vue')['default']
    IntegrationDetailsCard: typeof import('./src/components/IntegrationDetailsCard.vue')['default']
    IntegrationsOverview: typeof import('./src/components/IntegrationsOverview.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NotificationDetailsCard: typeof import('./src/components/NotificationDetailsCard.vue')['default']
    NotificationsOveview: typeof import('./src/components/NotificationsOveview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VirtualTable: typeof import('./src/components/VirtualTable.vue')['default']
    WorkflowCardDetails: typeof import('./src/components/WorkflowCardDetails.vue')['default']
    WorkflowOverview: typeof import('./src/components/WorkflowOverview.vue')['default']
  }
}
