name: CD frontend
on:
  push:
    branches:
      - main
    paths:
      - "04_frontend/**"
      - ".github/workflows/cd_frontend.yaml"
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./04_frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          aws s3 sync dist/. s3://${{ env.FRONTEND_S3_BUCKET_NAME }}/ --cache-control max-age=604800 --exclude "*.html"
          aws s3 sync dist/. s3://${{ env.FRONTEND_S3_BUCKET_NAME }}/ --cache-control max-age=60 --include "*.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
