name: CI frontend
on:
  pull_request:
    paths:
      - "04_frontend/**"
      - ".github/workflows/ci_frontend.yaml"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./04_frontend
    concurrency:
      group: 04_frontend-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./04_frontend/package.json
          cache: "npm"
          cache-dependency-path: ./04_frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_HOST_URL: ${{ vars.VITE_HOST_URL }}
          VITE_COGNITO_USER_POOL_ID: ${{ vars.VITE_COGNITO_USER_POOL_ID }}
          VITE_COGNITO_USER_POOL_CLIENT_ID: ${{ vars.VITE_COGNITO_USER_POOL_CLIENT_ID }}
          VITE_COGNITO_DOMAIN: ${{ vars.VITE_COGNITO_DOMAIN }}
          VITE_GRAPHQL_ENDPOINT: ${{ vars.VITE_GRAPHQL_ENDPOINT }}
          VITE_GRAPHQL_REGION: ${{ vars.VITE_GRAPHQL_REGION }}
          VITE_IMPORT_URL_BASE: ${{ vars.VITE_IMPORT_URL_BASE }}
