name: CI processor lambda
on:
  pull_request:
    paths:
      - "02_central/package.json"
      - "02_central/package-lock.json"
      - ".github/workflows/ci_processor_lambda.yaml"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./02_central
    concurrency:
      group: 02_central-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./02_central/package.json
          cache: "npm"
          cache-dependency-path: ./02_central/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
