name: Generate testdata

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "foobar"

      - name: step two
        run: echo "barfoo"
